In [1]:
import pandas as pd

In [16]:
education_df = pd.read_csv("./datatest/education_county_2023.csv", dtype={"FIPS Code": str})

# Create new column "Pop25+!HighSchool+!Percentage"
# = HighSchool or Higher / Population 25+ years
education_df["Pop25+!HighSchool+!Percentage"] = education_df["Population 25 years and over!Cumulative!High school graduate or higher"] / education_df["Population 25 years and over"]

# Create new column "Pop25+!BachelorsDegree+!Percentage"
# = Bachelors Degree or Higher / Population 25+ years
education_df["Pop25+!BachelorsDegree+!Percentage"] = education_df["Population 25 years and over!Cumulative!Bachelors degree or higher"] / education_df["Population 25 years and over"]

# Drop columns that are no longer needed
education_df = education_df.drop(["Population 25 years and over!Cumulative!Bachelors degree or higher", "Population 25 years and over!Cumulative!High school graduate or higher", "Population 25 years and over"], axis=1)

education_df.head()

,FIPS Code,County Name,State Name,Pop25+!HighSchool+!Percentage,Pop25+!BachelorsDegree+!Percentage
0,01001,Autauga County,Alabama,0.902789,0.282827
1,01003,Baldwin County,Alabama,0.917314,0.327976
2,01005,Barbour County,Alabama,0.778137,0.114647
3,01007,Bibb County,Alabama,0.803402,0.114682
4,01009,Blount County,Alabama,0.826962,0.155790

In [21]:
internetaccess_df = pd.read_csv("./datatest/internetaccess_county_2023.csv", dtype={"FIPS Code": str})

# Create new column "Households!WithInternetSubscription!Percentage"
# = Households With an Internet Subscription / Total Households
internetaccess_df["Households!WithInternetSubscription!Percentage"] = internetaccess_df["Households!With an Internet Subscription"] / internetaccess_df["Total Households"]

# Drop columns that are no longer needed
internetaccess_df = internetaccess_df.drop(["Households!With an Internet Subscription", "Total Households"], axis=1)

internetaccess_df.head()

,FIPS Code,County Name,State Name,Households!WithInternetSubscription!Percentage
0,01001,Autauga County,Alabama,0.909470
1,01003,Baldwin County,Alabama,0.898988
2,01005,Barbour County,Alabama,0.723018
3,01007,Bibb County,Alabama,0.813631
4,01009,Blount County,Alabama,0.844110

In [24]:
meanincome_df = pd.read_csv("./datatest/meanincome_county_2023.csv", dtype={"FIPS Code": str})

# Rename column
meanincome_df.rename(columns={"Households!Mean Income": "Housholds!MeanIncome"}, inplace = True)

# Drop columns that are no longer needed
meanincome_df = meanincome_df.drop(["Total Households"], axis=1)

meanincome_df.head()

  FIPS Code     County Name State Name  Housholds!MeanIncome
0     01001  Autauga County    Alabama                 93367
1     01003  Baldwin County    Alabama                100105
2     01005  Barbour County    Alabama                 64745
3     01007     Bibb County    Alabama                 67735
4     01009   Blount County    Alabama                 79203

In [28]:
fertilityrate_df = pd.read_csv("./datatest/fertilityrate_county_2023.csv", dtype={"FIPS Code": str})

# The general fertility rate (GFR) measures births per 1,000 women of childbearing age (15-50)
# Create new column "GeneralFertilityRate"
# = (Number of women with births in the past year / Total number of women aged 15-50)×1000
fertilityrate_df["GeneralFertilityRate"] = (fertilityrate_df["Women 15 to 50 years!Women with births in the last 12 months"] / fertilityrate_df["Total Women 15 to 50 years"]) * 1000


# Drop columns that are no longer needed
fertilityrate_df = fertilityrate_df.drop(["Women 15 to 50 years!Women with births in the last 12 months", "Total Women 15 to 50 years"], axis=1)

fertilityrate_df.head()

  FIPS Code     County Name State Name  GeneralFertilityRate
0     01001  Autauga County    Alabama             43.349210
1     01003  Baldwin County    Alabama             39.538320
2     01005  Barbour County    Alabama             50.075545
3     01007     Bibb County    Alabama             67.952652
4     01009   Blount County    Alabama             40.423484

In [31]:
householdsize_df = pd.read_csv("./datatest/householdsize_county_2023.csv", dtype={"FIPS Code": str})

# Rename column
householdsize_df.rename(columns={"AvgHouseholdSize": "Average Household Size"}, inplace = True)

householdsize_df.head()

,FIPS Code,County Name,State Name,Total Households,Households!Average Household Size
0,01001,Autauga County,Alabama,22523.0,2.61
1,01003,Baldwin County,Alabama,94642.0,2.50
2,01005,Barbour County,Alabama,9080.0,2.39
3,01007,Bibb County,Alabama,7571.0,2.74
4,01009,Blount County,Alabama,21977.0,2.67

In [ ]:
industrycomposition_df = pd.read_csv("./datatest/industrycomposition_county_2023.csv", dtype={"FIPS Code": str})

industrycomposition_df["16+Employed!AgricultureForestryFishingHuntingMining!Percentage"] = industrycomposition_df["16+ Employed!Agriculture, forestry, fishing and hunting, and mining"] / fertilityrate_df["Total 16+ Employed"]


industrycomposition_df["16+Employed!Construction!Percentage"] = industrycomposition_df["16+ Employed!Construction"] / fertilityrate_df["Total 16+ Employed"]




industrycomposition = industrycomposition_df.drop(
    ["16+ Employed!Agriculture, forestry, fishing and hunting, and mining",
     "16+ Employed!Construction",
     
     
     
     ],axis=1)

In [ ]:
industrycomposition_df_columns = list(industrycomposition_df.columns)

industrycomposition_df["16+Employed!AgricultureForestryFishingHuntingMining!Percentage"] = industrycomposition_df["16+ Employed!Agriculture, forestry, fishing and hunting, and mining"] / fertilityrate_df["Total 16+ Employed"]

for column in industrycomposition_df_columns: 
    print(column)

FIPS Code
County Name
State Name
Total 16+ Employed
16+ Employed!Agriculture, forestry, fishing and hunting, and mining
16+ Employed!Construction
16+ Employed!Manufacturing
16+ Employed!Wholesale Trade
16+ Employed!Retail Trade
16+ Employed!Transportation and warehousing, and utilities
16+ Employed!Information
16+ Employed!Finance and insurance, and real estate and rental and leasing
16+ Employed!Professional, scientific, and management, and administrative and waste management services
16+ Employed!Educational services, and health care and social assistance
16+ Employed!Arts, entertainment, and recreation, and accommodation and food services
16+ Employed!Other services, except public administration
16+ Employed!Public administration