In [10]:
import pandas as pd

In [11]:
education_df = pd.read_csv("./datatest/education_county_2023.csv", dtype={"FIPS Code": str})

# Create new column "Pop25+!HighSchool+!Percentage"
# = HighSchool or Higher / Population 25+ years
education_df["Pop25+!HighSchool+!Percentage"] = education_df["Population 25 years and over!Cumulative!High school graduate or higher"] / education_df["Population 25 years and over"]

# Create new column "Pop25+!BachelorsDegree+!Percentage"
# = Bachelors Degree or Higher / Population 25+ years
education_df["Pop25+!BachelorsDegree+!Percentage"] = education_df["Population 25 years and over!Cumulative!Bachelors degree or higher"] / education_df["Population 25 years and over"]

# Drop columns that are no longer needed
education_df = education_df.drop(["Population 25 years and over!Cumulative!Bachelors degree or higher", "Population 25 years and over!Cumulative!High school graduate or higher", "Population 25 years and over"], axis=1)

education_df.head()

,FIPS Code,County Name,State Name,Pop25+!HighSchool+!Percentage,Pop25+!BachelorsDegree+!Percentage
0,01001,Autauga County,Alabama,0.902789,0.282827
1,01003,Baldwin County,Alabama,0.917314,0.327976
2,01005,Barbour County,Alabama,0.778137,0.114647
3,01007,Bibb County,Alabama,0.803402,0.114682
4,01009,Blount County,Alabama,0.826962,0.155790

In [12]:
internetaccess_df = pd.read_csv("./datatest/internetaccess_county_2023.csv", dtype={"FIPS Code": str})

# Create new column "Households!WithInternetSubscription!Percentage"
# = Households With an Internet Subscription / Total Households
internetaccess_df["Households!WithInternetSubscription!Percentage"] = internetaccess_df["Households!With an Internet Subscription"] / internetaccess_df["Total Households"]

# Drop columns that are no longer needed
internetaccess_df = internetaccess_df.drop(["Households!With an Internet Subscription", "Total Households"], axis=1)

internetaccess_df.head()

,FIPS Code,County Name,State Name,Households!WithInternetSubscription!Percentage
0,01001,Autauga County,Alabama,0.909470
1,01003,Baldwin County,Alabama,0.898988
2,01005,Barbour County,Alabama,0.723018
3,01007,Bibb County,Alabama,0.813631
4,01009,Blount County,Alabama,0.844110

In [13]:
meanincome_df = pd.read_csv("./datatest/meanincome_county_2023.csv", dtype={"FIPS Code": str})

# Rename column
meanincome_df.rename(columns={"Households!Mean Income": "Housholds!MeanIncome"}, inplace = True)

# Drop columns that are no longer needed
meanincome_df = meanincome_df.drop(["Total Households"], axis=1)

meanincome_df.head()

  FIPS Code     County Name State Name  Housholds!MeanIncome
0     01001  Autauga County    Alabama                 93367
1     01003  Baldwin County    Alabama                100105
2     01005  Barbour County    Alabama                 64745
3     01007     Bibb County    Alabama                 67735
4     01009   Blount County    Alabama                 79203

In [14]:
fertilityrate_df = pd.read_csv("./datatest/fertilityrate_county_2023.csv", dtype={"FIPS Code": str})

# The general fertility rate (GFR) measures births per 1,000 women of childbearing age (15-50)
# Create new column "GeneralFertilityRate"
# = (Number of women with births in the past year / Total number of women aged 15-50)×1000
fertilityrate_df["GeneralFertilityRate"] = (fertilityrate_df["Women 15 to 50 years!Women with births in the last 12 months"] / fertilityrate_df["Total Women 15 to 50 years"]) * 1000


# Drop columns that are no longer needed
fertilityrate_df = fertilityrate_df.drop(["Women 15 to 50 years!Women with births in the last 12 months", "Total Women 15 to 50 years"], axis=1)

fertilityrate_df.head()

  FIPS Code     County Name State Name  GeneralFertilityRate
0     01001  Autauga County    Alabama             43.349210
1     01003  Baldwin County    Alabama             39.538320
2     01005  Barbour County    Alabama             50.075545
3     01007     Bibb County    Alabama             67.952652
4     01009   Blount County    Alabama             40.423484

In [15]:
householdsize_df = pd.read_csv("./datatest/householdsize_county_2023.csv", dtype={"FIPS Code": str})

# Rename column
householdsize_df.rename(columns={"AvgHouseholdSize": "Average Household Size"}, inplace = True)

householdsize_df.rename(columns={"Total Households": "Households!Total"}, inplace = True)

householdsize_df.head()

,FIPS Code,County Name,State Name,Households!Total,Households!Average Household Size
0,01001,Autauga County,Alabama,22523.0,2.61
1,01003,Baldwin County,Alabama,94642.0,2.50
2,01005,Barbour County,Alabama,9080.0,2.39
3,01007,Bibb County,Alabama,7571.0,2.74
4,01009,Blount County,Alabama,21977.0,2.67

In [31]:
industrycomposition_df = pd.read_csv("./datatest/industrycomposition_county_2023.csv", dtype={"FIPS Code": str})


# Calculate Percentages

industrycomposition_df["16+Employed!AgricultureForestryFishingHuntingMining!Percentage"] = industrycomposition_df["16+ Employed!Agriculture, forestry, fishing and hunting, and mining"] / industrycomposition_df["Total 16+ Employed"]

industrycomposition_df["16+Employed!Construction!Percentage"] = industrycomposition_df["16+ Employed!Construction"] / industrycomposition_df["Total 16+ Employed"]

industrycomposition_df["16+Employed!Manufacturing!Percentage"] = industrycomposition_df["16+ Employed!Manufacturing"] / industrycomposition_df["Total 16+ Employed"]

industrycomposition_df["16+Employed!Wholesaletrade!Percentage"] = industrycomposition_df["16+ Employed!Wholesale Trade"] / industrycomposition_df["Total 16+ Employed"]

industrycomposition_df["16+Employed!Retailtrade!Percentage"] = industrycomposition_df["16+ Employed!Retail Trade"] / industrycomposition_df["Total 16+ Employed"]

industrycomposition_df["16+Employed!TransportationWarehousingUtilities!Percentage"] = industrycomposition_df["16+ Employed!Transportation and warehousing, and utilities"] / industrycomposition_df["Total 16+ Employed"]

industrycomposition_df["16+Employed!Information!Percentage"] = industrycomposition_df["16+ Employed!Information"] / industrycomposition_df["Total 16+ Employed"]

industrycomposition_df["16+Employed!FinanceInsuranceRealestate!Percentage"] = industrycomposition_df["16+ Employed!Finance and insurance, and real estate and rental and leasing"] / industrycomposition_df["Total 16+ Employed"]

industrycomposition_df["16+Employed!ProfessionalScientificManagementAdministrativeServices!Percentage"] = industrycomposition_df["16+ Employed!Professional, scientific, and management, and administrative and waste management services"] / industrycomposition_df["Total 16+ Employed"]

industrycomposition_df["16+Employed!EducationHealthcareSocialassistance!Percentage"] = industrycomposition_df["16+ Employed!Educational services, and health care and social assistance"] / industrycomposition_df["Total 16+ Employed"]

industrycomposition_df["16+Employed!ArtsEntertainmentRecreationAccommodationFood!Percentage"] = industrycomposition_df["16+ Employed!Arts, entertainment, and recreation, and accommodation and food services"] / industrycomposition_df["Total 16+ Employed"]

industrycomposition_df["16+Employed!Otherservices!Percentage"] = industrycomposition_df["16+ Employed!Other services, except public administration"] / industrycomposition_df["Total 16+ Employed"]

industrycomposition_df["16+Employed!Publicadministration!Percentage"] = industrycomposition_df["16+ Employed!Public administration"] / industrycomposition_df["Total 16+ Employed"]

# Rename

industrycomposition_df.rename(columns={"Total 16+ Employed": "16+Employed!Total"}, inplace = True)

# Drop Columns 

industrycomposition_df = industrycomposition_df.drop(
    ["16+ Employed!Agriculture, forestry, fishing and hunting, and mining",
     "16+ Employed!Construction",
     "16+ Employed!Manufacturing",
     "16+ Employed!Wholesale Trade",
     "16+ Employed!Retail Trade",
     "16+ Employed!Transportation and warehousing, and utilities",
     "16+ Employed!Information",
     "16+ Employed!Finance and insurance, and real estate and rental and leasing",
     "16+ Employed!Professional, scientific, and management, and administrative and waste management services",
     "16+ Employed!Educational services, and health care and social assistance",
     "16+ Employed!Arts, entertainment, and recreation, and accommodation and food services",
     "16+ Employed!Other services, except public administration",
     "16+ Employed!Public administration"
     ],axis=1)

In [32]:
industrycomposition_df.head()

,FIPS Code,County Name,State Name,16+Employed!Total,16+Employed!AgricultureForestryFishingHuntingMining!Percentage,16+Employed!Construction!Percentage,16+Employed!Manufacturing!Percentage,16+Employed!Wholesaletrade!Percentage,16+Employed!Retailtrade!Percentage,16+Employed!TransportationWarehousingUtilities!Percentage,16+Employed!Information!Percentage,16+Employed!FinanceInsuranceRealestate!Percentage,16+Employed!ProfessionalScientificManagementAdministrativeServices!Percentage,16+Employed!EducationHealthcareSocialassistance!Percentage,16+Employed!ArtsEntertainmentRecreationAccommodationFood!Percentage,16+Employed!Otherservices!Percentage,16+Employed!Publicadministration!Percentage
0,01001,Autauga County,Alabama,26382,0.009855,0.072360,0.116974,0.029262,0.121901,0.056667,0.012925,0.057994,0.090630,0.189826,0.101395,0.036881,0.103328
1,01003,Baldwin County,Alabama,109556,0.017352,0.081940,0.098151,0.019807,0.146172,0.049500,0.008872,0.071352,0.118277,0.192532,0.101072,0.049418,0.045557
2,01005,Barbour County,Alabama,8556,0.041608,0.052945,0.227209,0.005844,0.099696,0.068373,0.005376,0.035414,0.052127,0.213768,0.086138,0.029687,0.081814
3,01007,Bibb County,Alabama,8439,0.026662,0.101552,0.163408,0.029032,0.134969,0.057353,0.008413,0.058656,0.083185,0.200735,0.034246,0.054746,0.047043
4,01009,Blount County,Alabama,25594,0.022232,0.093420,0.163515,0.032976,0.132258,0.077440,0.009416,0.047902,0.078026,0.195515,0.059115,0.052669,0.035516

In [22]:
industrycomposition_df_columns = list(industrycomposition_df.columns)

for column in industrycomposition_df_columns: 
    print(column)

FIPS Code
County Name
State Name
16+Employed!Total
16+Employed!AgricultureForestryFishingHuntingMining!Percentage
16+Employed!Construction!Percentage
16+Employed!Manufacturing!Percentage
16+Employed!Wholesaletrade!Percentage
16+Employed!Retailtrade!Percentage
16+Employed!TransportationWarehousingUtilities!Percentage
16+Employed!FinanceInsuranceRealestate!Percentage
16+Employed!ProfessionalScientificManagementAdministrativeServices!Percentage
16+Employed!EducationHealthcareSocialassistance!Percentage
16+Employed!ArtsEntertainmentRecreationAccommodationFood!Percentage
16+Employed!Otherservices!Percentage
16+Employed!Publicadministration!Percentage

In [ ]:
education_df

internetaccess_df

meanincome_df

fertilityrate_df

householdsize_df

industrycomposition_df

In [24]:
from functools import reduce

In [33]:

dfs = [education_df, internetaccess_df, meanincome_df, fertilityrate_df, householdsize_df, industrycomposition_df]

merged_df = reduce(lambda left, right: pd.merge(left, right, on=["FIPS Code", "County Name", "State Name"], how="inner"), dfs)

merged_df.head(200)

,FIPS Code,County Name,State Name,Pop25+!HighSchool+!Percentage,Pop25+!BachelorsDegree+!Percentage,Households!WithInternetSubscription!Percentage,Housholds!MeanIncome,GeneralFertilityRate,Households!Total,Households!Average Household Size,...,16+Employed!Wholesaletrade!Percentage,16+Employed!Retailtrade!Percentage,16+Employed!TransportationWarehousingUtilities!Percentage,16+Employed!Information!Percentage,16+Employed!FinanceInsuranceRealestate!Percentage,16+Employed!ProfessionalScientificManagementAdministrativeServices!Percentage,16+Employed!EducationHealthcareSocialassistance!Percentage,16+Employed!ArtsEntertainmentRecreationAccommodationFood!Percentage,16+Employed!Otherservices!Percentage,16+Employed!Publicadministration!Percentage
0,01001,Autauga County,Alabama,0.902789,0.282827,0.909470,93367,43.349210,22523.0,2.61,...,0.029262,0.121901,0.056667,0.012925,0.057994,0.090630,0.189826,0.101395,0.036881,0.103328
1,01003,Baldwin County,Alabama,0.917314,0.327976,0.898988,100105,39.538320,94642.0,2.50,...,0.019807,0.146172,0.049500,0.008872,0.071352,0.118277,0.192532,0.101072,0.049418,0.045557
2,01005,Barbour County,Alabama,0.778137,0.114647,0.723018,64745,50.075545,9080.0,2.39,...,0.005844,0.099696,0.068373,0.005376,0.035414,0.052127,0.213768,0.086138,0.029687,0.081814
3,01007,Bibb County,Alabama,0.803402,0.114682,0.813631,67735,67.952652,7571.0,2.74,...,0.029032,0.134969,0.057353,0.008413,0.058656,0.083185,0.200735,0.034246,0.054746,0.047043
4,01009,Blount County,Alabama,0.826962,0.155790,0.844110,79203,40.423484,21977.0,2.67,...,0.032976,0.132258,0.077440,0.009416,0.047902,0.078026,0.195515,0.059115,0.052669,0.035516
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,06017,El Dorado County,California,0.949165,0.388241,0.924286,145804,48.537731,75719.0,2.51,...,0.017191,0.098191,0.041353,0.018203,0.070744,0.134973,0.213232,0.122852,0.048220,0.070869
196,06019,Fresno County,California,0.785969,0.238545,0.873263,97005,58.804322,322163.0,3.08,...,0.028380,0.100630,0.067661,0.011667,0.042894,0.093571,0.258713,0.082629,0.046888,0.061886
197,06021,Glenn County,California,0.803232,0.164823,0.905357,86148,60.053451,9763.0,2.91,...,0.009608,0.125600,0.058190,0.000697,0.030141,0.050519,0.205098,0.069193,0.069812,0.062452
198,06023,Humboldt County,California,0.915183,0.320851,0.906319,86742,32.320205,54878.0,2.39,...,0.015433,0.116843,0.038691,0.014647,0.038474,0.099035,0.253248,0.109870,0.055579,0.083669
199,06025,Imperial County,California,0.718471,0.161003,0.883650,77390,57.611406,48844.0,3.51,...,0.024780,0.117185,0.066581,0.008103,0.032068,0.074455,0.237516,0.092698,0.044001,0.107077

In [34]:
merged_df_columns = list(merged_df.columns)

for column in merged_df_columns: 
    print(column)

FIPS Code
County Name
State Name
Pop25+!HighSchool+!Percentage
Pop25+!BachelorsDegree+!Percentage
Households!WithInternetSubscription!Percentage
Housholds!MeanIncome
GeneralFertilityRate
Households!Total
Households!Average Household Size
16+Employed!Total
16+Employed!AgricultureForestryFishingHuntingMining!Percentage
16+Employed!Construction!Percentage
16+Employed!Manufacturing!Percentage
16+Employed!Wholesaletrade!Percentage
16+Employed!Retailtrade!Percentage
16+Employed!TransportationWarehousingUtilities!Percentage
16+Employed!Information!Percentage
16+Employed!FinanceInsuranceRealestate!Percentage
16+Employed!ProfessionalScientificManagementAdministrativeServices!Percentage
16+Employed!EducationHealthcareSocialassistance!Percentage
16+Employed!ArtsEntertainmentRecreationAccommodationFood!Percentage
16+Employed!Otherservices!Percentage
16+Employed!Publicadministration!Percentage

In [42]:
df_sorted = merged_df.sort_values(by="Housholds!MeanIncome", ascending=False)

In [44]:
df_sorted = df_sorted [["FIPS Code", 
                        "County Name", 
                        "State Name",
                        "Pop25+!BachelorsDegree+!Percentage",
                        "Housholds!MeanIncome",
                        "16+Employed!Information!Percentage",
                        "16+Employed!FinanceInsuranceRealestate!Percentage",
                        "16+Employed!ProfessionalScientificManagementAdministrativeServices!Percentage"
                        ]]

In [45]:
df_sorted.head(20)

,FIPS Code,County Name,State Name,Pop25+!BachelorsDegree+!Percentage,Housholds!MeanIncome,16+Employed!Information!Percentage,16+Employed!FinanceInsuranceRealestate!Percentage,16+Employed!ProfessionalScientificManagementAdministrativeServices!Percentage
227,06081,San Mateo County,California,0.530712,226660,0.048572,0.067804,0.214717
207,06041,Marin County,California,0.604592,224140,0.043001,0.088155,0.219129
229,06085,Santa Clara County,California,0.558656,219664,0.061631,0.043148,0.227345
2874,51107,Loudoun County,Virginia,0.640137,209947,0.037317,0.078504,0.295545
317,09190,Western Connecticut Planning Region,Connecticut,0.550458,209168,0.031391,0.130217,0.173226
2800,49043,Summit County,Utah,0.580697,208695,0.020913,0.112321,0.149747
2927,51610,Falls Church city,Virginia,0.797257,205626,0.017485,0.063898,0.304063
224,06075,San Francisco County,California,0.601208,204625,0.063239,0.085779,0.266744
294,08097,Pitkin County,Colorado,0.639695,200851,0.024944,0.107041,0.161740
1228,25019,Nantucket County,Massachusetts,0.583828,194491,0.005409,0.048924,0.214751
1860,36061,New York County,New York,0.640028,192391,0.057393,0.160167,0.214604
2850,51059,Fairfax County,Virginia,0.642670,191191,0.024126,0.072515,0.268650
1859,36059,Nassau County,New York,0.487138,187735,0.024284,0.100547,0.132505
1889,36119,Westchester County,New York,0.525100,187481,0.031863,0.102821,0.156140
1793,34035,Somerset County,New Jersey,0.573510,186372,0.037100,0.095875,0.175422
3140,56039,Teton County,Wyoming,0.612197,185173,0.032850,0.089346,0.123539
2828,51013,Arlington County,Virginia,0.771092,184356,0.028939,0.073573,0.303708
1785,34019,Hunterdon County,New Jersey,0.564997,182668,0.029728,0.088192,0.159145
1789,34027,Morris County,New Jersey,0.572473,181402,0.029081,0.100809,0.171553
1207,24027,Howard County,Maryland,0.644754,180793,0.020111,0.064231,0.212334