In [15]:
import pandas as pd

In [16]:
education_df = pd.read_csv("./datatest/education_county_2023.csv", dtype={"FIPS Code": str})

# Create new column "Pop25+!HighSchool+!Percentage"
# = HighSchool or Higher / Population 25+ years
education_df["Pop25+!HighSchool+!Percentage"] = education_df["Population 25 years and over!Cumulative!High school graduate or higher"] / education_df["Population 25 years and over"]

# Create new column "Pop25+!BachelorsDegree+!Percentage"
# = Bachelors Degree or Higher / Population 25+ years
education_df["Pop25+!BachelorsDegree+!Percentage"] = education_df["Population 25 years and over!Cumulative!Bachelors degree or higher"] / education_df["Population 25 years and over"]

# Drop columns that are no longer needed
education_df = education_df.drop(["Population 25 years and over!Cumulative!Bachelors degree or higher", "Population 25 years and over!Cumulative!High school graduate or higher", "Population 25 years and over"], axis=1)

education_df.head()

,FIPS Code,County Name,State Name,Pop25+!HighSchool+!Percentage,Pop25+!BachelorsDegree+!Percentage
0,01001,Autauga County,Alabama,0.902789,0.282827
1,01003,Baldwin County,Alabama,0.917314,0.327976
2,01005,Barbour County,Alabama,0.778137,0.114647
3,01007,Bibb County,Alabama,0.803402,0.114682
4,01009,Blount County,Alabama,0.826962,0.155790

In [17]:
internetaccess_df = pd.read_csv("./datatest/internetaccess_county_2023.csv", dtype={"FIPS Code": str})

# Create new column "Households!WithInternetSubscription!Percentage"
# = Households With an Internet Subscription / Total Households
internetaccess_df["Households!WithInternetSubscription!Percentage"] = internetaccess_df["Households!With an Internet Subscription"] / internetaccess_df["Total Households"]

# Drop columns that are no longer needed
internetaccess_df = internetaccess_df.drop(["Households!With an Internet Subscription", "Total Households"], axis=1)

internetaccess_df.head()

,FIPS Code,County Name,State Name,Households!WithInternetSubscription!Percentage
0,01001,Autauga County,Alabama,0.909470
1,01003,Baldwin County,Alabama,0.898988
2,01005,Barbour County,Alabama,0.723018
3,01007,Bibb County,Alabama,0.813631
4,01009,Blount County,Alabama,0.844110

In [18]:
meanincome_df = pd.read_csv("./datatest/meanincome_county_2023.csv", dtype={"FIPS Code": str})

# Rename column
meanincome_df.rename(columns={"Households!Mean Income": "Housholds!MeanIncome"}, inplace = True)

# Drop columns that are no longer needed
meanincome_df = meanincome_df.drop(["Total Households"], axis=1)

meanincome_df.head()

  FIPS Code     County Name State Name  Housholds!MeanIncome
0     01001  Autauga County    Alabama                 93367
1     01003  Baldwin County    Alabama                100105
2     01005  Barbour County    Alabama                 64745
3     01007     Bibb County    Alabama                 67735
4     01009   Blount County    Alabama                 79203

In [19]:
fertilityrate_df = pd.read_csv("./datatest/fertilityrate_county_2023.csv", dtype={"FIPS Code": str})

# The general fertility rate (GFR) measures births per 1,000 women of childbearing age (15-50)
# Create new column "GeneralFertilityRate"
# = (Number of women with births in the past year / Total number of women aged 15-50)×1000
fertilityrate_df["GeneralFertilityRate"] = (fertilityrate_df["Women 15 to 50 years!Women with births in the last 12 months"] / fertilityrate_df["Total Women 15 to 50 years"]) * 1000


# Drop columns that are no longer needed
fertilityrate_df = fertilityrate_df.drop(["Women 15 to 50 years!Women with births in the last 12 months", "Total Women 15 to 50 years"], axis=1)

fertilityrate_df.head()

  FIPS Code     County Name State Name  GeneralFertilityRate
0     01001  Autauga County    Alabama             43.349210
1     01003  Baldwin County    Alabama             39.538320
2     01005  Barbour County    Alabama             50.075545
3     01007     Bibb County    Alabama             67.952652
4     01009   Blount County    Alabama             40.423484

In [20]:
householdsize_df = pd.read_csv("./datatest/householdsize_county_2023.csv", dtype={"FIPS Code": str})

# Rename column
householdsize_df.rename(columns={"AvgHouseholdSize": "Households!AverageSize"}, inplace = True)

householdsize_df.rename(columns={"Total Households": "Households!Total"}, inplace = True)

householdsize_df.head()

,FIPS Code,County Name,State Name,Households!Total,Households!Average Household Size
0,01001,Autauga County,Alabama,22523.0,2.61
1,01003,Baldwin County,Alabama,94642.0,2.50
2,01005,Barbour County,Alabama,9080.0,2.39
3,01007,Bibb County,Alabama,7571.0,2.74
4,01009,Blount County,Alabama,21977.0,2.67

In [21]:
industrycomposition_df = pd.read_csv("./datatest/industrycomposition_county_2023.csv", dtype={"FIPS Code": str})


# Calculate Percentages

industrycomposition_df["16+Employed!AgricultureForestryFishingHuntingMining!Percentage"] = industrycomposition_df["16+ Employed!Agriculture, forestry, fishing and hunting, and mining"] / industrycomposition_df["Total 16+ Employed"]

industrycomposition_df["16+Employed!Construction!Percentage"] = industrycomposition_df["16+ Employed!Construction"] / industrycomposition_df["Total 16+ Employed"]

industrycomposition_df["16+Employed!Manufacturing!Percentage"] = industrycomposition_df["16+ Employed!Manufacturing"] / industrycomposition_df["Total 16+ Employed"]

industrycomposition_df["16+Employed!Wholesaletrade!Percentage"] = industrycomposition_df["16+ Employed!Wholesale Trade"] / industrycomposition_df["Total 16+ Employed"]

industrycomposition_df["16+Employed!Retailtrade!Percentage"] = industrycomposition_df["16+ Employed!Retail Trade"] / industrycomposition_df["Total 16+ Employed"]

industrycomposition_df["16+Employed!TransportationWarehousingUtilities!Percentage"] = industrycomposition_df["16+ Employed!Transportation and warehousing, and utilities"] / industrycomposition_df["Total 16+ Employed"]

industrycomposition_df["16+Employed!Information!Percentage"] = industrycomposition_df["16+ Employed!Information"] / industrycomposition_df["Total 16+ Employed"]

industrycomposition_df["16+Employed!FinanceInsuranceRealestate!Percentage"] = industrycomposition_df["16+ Employed!Finance and insurance, and real estate and rental and leasing"] / industrycomposition_df["Total 16+ Employed"]

industrycomposition_df["16+Employed!ProfessionalScientificManagementAdministrativeServices!Percentage"] = industrycomposition_df["16+ Employed!Professional, scientific, and management, and administrative and waste management services"] / industrycomposition_df["Total 16+ Employed"]

industrycomposition_df["16+Employed!EducationHealthcareSocialassistance!Percentage"] = industrycomposition_df["16+ Employed!Educational services, and health care and social assistance"] / industrycomposition_df["Total 16+ Employed"]

industrycomposition_df["16+Employed!ArtsEntertainmentRecreationAccommodationFood!Percentage"] = industrycomposition_df["16+ Employed!Arts, entertainment, and recreation, and accommodation and food services"] / industrycomposition_df["Total 16+ Employed"]

industrycomposition_df["16+Employed!Otherservices!Percentage"] = industrycomposition_df["16+ Employed!Other services, except public administration"] / industrycomposition_df["Total 16+ Employed"]

industrycomposition_df["16+Employed!Publicadministration!Percentage"] = industrycomposition_df["16+ Employed!Public administration"] / industrycomposition_df["Total 16+ Employed"]

# Rename

industrycomposition_df.rename(columns={"Total 16+ Employed": "16+Employed!Total"}, inplace = True)

# Drop Columns 

industrycomposition_df = industrycomposition_df.drop(
    ["16+ Employed!Agriculture, forestry, fishing and hunting, and mining",
     "16+ Employed!Construction",
     "16+ Employed!Manufacturing",
     "16+ Employed!Wholesale Trade",
     "16+ Employed!Retail Trade",
     "16+ Employed!Transportation and warehousing, and utilities",
     "16+ Employed!Information",
     "16+ Employed!Finance and insurance, and real estate and rental and leasing",
     "16+ Employed!Professional, scientific, and management, and administrative and waste management services",
     "16+ Employed!Educational services, and health care and social assistance",
     "16+ Employed!Arts, entertainment, and recreation, and accommodation and food services",
     "16+ Employed!Other services, except public administration",
     "16+ Employed!Public administration"
     ],axis=1)

industrycomposition_df.head()

,FIPS Code,County Name,State Name,16+Employed!Total,16+Employed!AgricultureForestryFishingHuntingMining!Percentage,16+Employed!Construction!Percentage,16+Employed!Manufacturing!Percentage,16+Employed!Wholesaletrade!Percentage,16+Employed!Retailtrade!Percentage,16+Employed!TransportationWarehousingUtilities!Percentage,16+Employed!Information!Percentage,16+Employed!FinanceInsuranceRealestate!Percentage,16+Employed!ProfessionalScientificManagementAdministrativeServices!Percentage,16+Employed!EducationHealthcareSocialassistance!Percentage,16+Employed!ArtsEntertainmentRecreationAccommodationFood!Percentage,16+Employed!Otherservices!Percentage,16+Employed!Publicadministration!Percentage
0,01001,Autauga County,Alabama,26382,0.009855,0.072360,0.116974,0.029262,0.121901,0.056667,0.012925,0.057994,0.090630,0.189826,0.101395,0.036881,0.103328
1,01003,Baldwin County,Alabama,109556,0.017352,0.081940,0.098151,0.019807,0.146172,0.049500,0.008872,0.071352,0.118277,0.192532,0.101072,0.049418,0.045557
2,01005,Barbour County,Alabama,8556,0.041608,0.052945,0.227209,0.005844,0.099696,0.068373,0.005376,0.035414,0.052127,0.213768,0.086138,0.029687,0.081814
3,01007,Bibb County,Alabama,8439,0.026662,0.101552,0.163408,0.029032,0.134969,0.057353,0.008413,0.058656,0.083185,0.200735,0.034246,0.054746,0.047043
4,01009,Blount County,Alabama,25594,0.022232,0.093420,0.163515,0.032976,0.132258,0.077440,0.009416,0.047902,0.078026,0.195515,0.059115,0.052669,0.035516

In [22]:
demographics_df = pd.read_csv("./datatest/demographics_county_2023.csv", dtype={"FIPS Code": str})

# Rename column
demographics_df.rename(columns={"Median Age": "MedianAge", 
                                "Sex Ratio": "SexRatio"
                                }, inplace = True)


# Drop columns that are no longer needed
demographics_df = demographics_df.drop(["Total Population"], axis=1)

demographics_df.head()

  FIPS Code     County Name State Name  MedianAge  SexRatio
0     01001  Autauga County    Alabama       39.2      93.6
1     01003  Baldwin County    Alabama       43.7      95.7
2     01005  Barbour County    Alabama       40.7     108.9
3     01007     Bibb County    Alabama       41.3     114.5
4     01009   Blount County    Alabama       40.9     102.0

In [23]:
healthinsurance_df = pd.read_csv("./datatest/healthinsurance_county_2023.csv", dtype={"FIPS Code": str})

# Rename column
healthinsurance_df.rename(columns={"PopulationNonInstitutionalized!Insured!Percent": "HealthInsured!Percent"
                                }, inplace = True)


# Drop columns that are no longer needed
healthinsurance_df["HealthInsured!Percent"] = healthinsurance_df["HealthInsured!Percent"] / 100

healthinsurance_df.head()

  FIPS Code     County Name State Name  HealthInsured!Percent
0     01001  Autauga County    Alabama                  0.926
1     01003  Baldwin County    Alabama                  0.918
2     01005  Barbour County    Alabama                  0.892
3     01007     Bibb County    Alabama                  0.917
4     01009   Blount County    Alabama                  0.898

In [24]:
housingcost_df = pd.read_csv("./datatest/housingcost_county_2023.csv", dtype={"FIPS Code": str})


housingcost_df.head()

,FIPS Code,County Name,State Name,Median MonthlyHousingCost,OwnerOccupied!Median MonthlyHousingCost,RenterOccupied!Median MonthlyHousingCost
0,01001,Autauga County,Alabama,1048,953,1200
1,01003,Baldwin County,Alabama,1142,1098,1211
2,01005,Barbour County,Alabama,640,632,644
3,01007,Bibb County,Alabama,615,566,802
4,01009,Blount County,Alabama,741,746,743

In [25]:
housingtype_df = pd.read_csv("./datatest/housingtype_county_2023.csv", dtype={"FIPS Code": str})

# Rename column
housingtype_df.rename(columns={"Households!OwnerOccupiedUnits!Percent": "Households!OwnerOccupied!Percent",
                                   "Households!RenterOccupiedUnits!Percent": "Households!RenterOccupied!Percent"
                                }, inplace = True)


# Drop columns that are no longer needed
housingtype_df["Households!OwnerOccupied!Percent"] = housingtype_df["Households!OwnerOccupied!Percent"] / 100

housingtype_df["Households!RenterOccupied!Percent"] = housingtype_df["Households!RenterOccupied!Percent"] / 100

housingtype_df.head()

,FIPS Code,County Name,State Name,Households!OwnerOccupied!Percent,Households!RenterOccupied!Percent
0,01001,Autauga County,Alabama,0.749,0.251
1,01003,Baldwin County,Alabama,0.775,0.225
2,01005,Barbour County,Alabama,0.675,0.325
3,01007,Bibb County,Alabama,0.772,0.228
4,01009,Blount County,Alabama,0.795,0.205

In [26]:
laborforceparticipation_df = pd.read_csv("./datatest/laborforceparticipation_county_2023.csv", dtype={"FIPS Code": str})

# Rename column
laborforceparticipation_df.rename(columns={"LaborForceParticipation Rate": "LaborForceParticipation!Rate"
                                }, inplace = True)


# Drop columns that are no longer needed
laborforceparticipation_df["LaborForceParticipation!Rate"] = laborforceparticipation_df["LaborForceParticipation!Rate"] / 100

laborforceparticipation_df.head()

  FIPS Code     County Name State Name  LaborForceParticipation!Rate
0     01001  Autauga County    Alabama                         0.590
1     01003  Baldwin County    Alabama                         0.583
2     01005  Barbour County    Alabama                         0.449
3     01007     Bibb County    Alabama                         0.516
4     01009   Blount County    Alabama                         0.574

In [27]:
limitedenglish_df = pd.read_csv("./datatest/limitedenglish_county_2023.csv", dtype={"FIPS Code": str})


# Drop columns that are no longer needed
limitedenglish_df["Households!LimitedEnglishSpeaking!Percent"] = limitedenglish_df["Households!LimitedEnglishSpeaking!Percent"] / 100

limitedenglish_df.head()

,FIPS Code,County Name,State Name,Households!LimitedEnglishSpeaking!Percent
0,01001,Autauga County,Alabama,0.005
1,01003,Baldwin County,Alabama,0.008
2,01005,Barbour County,Alabama,0.025
3,01007,Bibb County,Alabama,0.007
4,01009,Blount County,Alabama,0.018

In [28]:
medianincome_df = pd.read_csv("./datatest/medianincome_county_2023.csv", dtype={"FIPS Code": str})

medianincome_df.head()

  FIPS Code     County Name State Name  Households!MedianIncome
0     01001  Autauga County    Alabama                    69841
1     01003  Baldwin County    Alabama                    75019
2     01005  Barbour County    Alabama                    44290
3     01007     Bibb County    Alabama                    51215
4     01009   Blount County    Alabama                    61096

In [29]:
from functools import reduce


dfs = [demographics_df,
       householdsize_df,
       laborforceparticipation_df,
       medianincome_df, 
       meanincome_df,
       fertilityrate_df,
       healthinsurance_df,
       education_df, 
       limitedenglish_df,
       internetaccess_df,
       housingcost_df,
       housingtype_df,
       industrycomposition_df]

merged_df = reduce(lambda left, right: pd.merge(left, right, on=["FIPS Code", "County Name", "State Name"], how="inner"), dfs)

merged_df.info()

merged_df.to_csv("datanew/data_uscensus_merged.csv", index = False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3144 entries, 0 to 3143
Data columns (total 35 columns):
 #   Column                                                                         Non-Null Count  Dtype
---  ------                                                                         --------------  -----
 0   FIPS Code                                                                      3144 non-null   object
 1   County Name                                                                    3144 non-null   object
 2   State Name                                                                     3144 non-null   object
 3   MedianAge                                                                      3144 non-null   float64
 4   SexRatio                                                                       3144 non-null   float64
 5   Households!Total                                                               3144 non-null   float64
 6   Households!Average Household Size                                              3144 non-null   float64
 7   LaborForceParticipation!Rate                                                   3144 non-null   float64
 8   Households!MedianIncome                                                        3144 non-null   int64
 9   Housholds!MeanIncome                                                           3144 non-null   int64
 10  GeneralFertilityRate                                                           3143 non-null   float64
 11  HealthInsured!Percent                                                          3144 non-null   float64
 12  Pop25+!HighSchool+!Percentage                                                  3144 non-null   float64
 13  Pop25+!BachelorsDegree+!Percentage                                             3144 non-null   float64
 14  Households!LimitedEnglishSpeaking!Percent                                      3144 non-null   float64
 15  Households!WithInternetSubscription!Percentage                                 3144 non-null   float64
 16  Median MonthlyHousingCost                                                      3144 non-null   int64
 17  OwnerOccupied!Median MonthlyHousingCost                                        3144 non-null   int64
 18  RenterOccupied!Median MonthlyHousingCost                                       3144 non-null   int64
 19  Households!OwnerOccupied!Percent                                               3144 non-null   float64
 20  Households!RenterOccupied!Percent                                              3144 non-null   float64
 21  16+Employed!Total                                                              3144 non-null   int64
 22  16+Employed!AgricultureForestryFishingHuntingMining!Percentage                 3144 non-null   float64
 23  16+Employed!Construction!Percentage                                            3144 non-null   float64
 24  16+Employed!Manufacturing!Percentage                                           3144 non-null   float64
 25  16+Employed!Wholesaletrade!Percentage                                          3144 non-null   float64
 26  16+Employed!Retailtrade!Percentage                                             3144 non-null   float64
 27  16+Employed!TransportationWarehousingUtilities!Percentage                      3144 non-null   float64
 28  16+Employed!Information!Percentage                                             3144 non-null   float64
 29  16+Employed!FinanceInsuranceRealestate!Percentage                              3144 non-null   float64
 30  16+Employed!ProfessionalScientificManagementAdministrativeServices!Percentage  3144 non-null   float64
 31  16+Employed!EducationHealthcareSocialassistance!Percentage                     3144 non-null   float64
 32  16+Employed!ArtsEntertainmentRecreationAccommodationFood!Percentage            3144 non-null   float64
 33  16+Employed!Otherservices!Percentage                                           3144 non-null   float64
 34  16+Employed!Publicadministration!Percentage                                    3144 non-null   float64
dtypes: float64(26), int64(6), object(3)
memory usage: 859.8+ KB